dataset: MNIST # 数据集名称，可选项包括MNIST, CIFAR-10, FMNIST

test_batch_size: 256 # 测试批量大小
learning_rate: 0.002 # 学习率, MNIST: 0.002, FMNIST: 0.001

# 训练开始所在轮数
start_round: 0

# 训练周期
epochs: 1

num_clients: 10 # 客户端数量

# 动量, 常用于加速SGD在相关方向上的导航，并抑制振荡
momentum: 0.9

iters: 100 # 迭代次数

# Dirichlet distribution alpha参数, 通常用于联邦学习场景
alpha: 0.05

seed: 1 # 随机种子，保证实验可重现性

# 以下是关于隐私保护参数的部分
q_for_batch_size: 0.01 # 数据采样率
max_norm: 1.0 # 用于梯度裁剪的最大范数
sigma: 6.0 # 隐私保护参数σ 参考值：1.0, 1.1
delta: 1e-5 # 隐私保护参数δ, 通常设置得很小

device: cuda # 训练设备，cpu或cuda
algorithm: fed_avg_with_dp_perlayer # 使用的算法，如fed_avg, fed_avg_with_dp, fed_avg_with_dp_perlayer, fed_avg_with_dp_auto, DPSGD

# 模型加载路径
save_dir: ./saved_states
